services:
  bind:
    image: ubuntu/bind9
    environment:
      TZ: UTC
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./docker/bind/db.punksecurity.io:/etc/bind/db.punksecurity.io"
      - "./docker/bind/named.conf.local:/etc/bind/named.conf.local"
      - "./docker/bind/named.conf.options:/etc/bind/named.conf.options"
