name: Build and publish release on new tag
on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # TODO: replace username with action variable
          username: punksecurity
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
        id: version
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/bake-action@v5
        env:
          VERSION: ${{ steps.version.outputs.version }}
        with:
          push: true
          targets: "release"
